### PR TITLE
Add an Overlapping Frames sample.

### PR DESCRIPTION
**Pull request by krmoule**
This sample renders a rotating triangle using overlapping frames, i.e. at each main loop iteration, parts of several frames' rendering are being submitted.

### CODE REVIEW

**Comment by krmoule** [comment]
@hevrard @nipunG314 can I get your consent on this per the google-cla comment above. Thanks!

**Comment by hevrard** [comment]
@googlebot I consent.

**Comment by nipunG314** [comment]
@google-admin I consent.

**Comment by AWoloszyn** [comment]
@nipunG314 I think you need to @googlebot rather than @google-admin

**Comment by nipunG314** [comment]
@googlebot I consent.

**Pull request merged**
