### PR TITLE
WIP: Tiny compute cl

### PR DESCRIPTION
**Pull request by dneto0**
Adds tiny_compute example with GLSL and OpenLC C variants.
Add simple support for compiling OpenCL C with "clspv".  Quite experimental compiler!

### CODE REVIEW

**Comment by dneto0** [comment]
Hmm.  clspv is going to be rare for a while.  So perhaps tiny_compute_cl should be enabled only if clspv is found / defined?

**Comment by dneto0** [comment]
The dependency tracking is messed up.  There's a broken dependency between the input shader source and the final -mfmt=c output.
Changed to WIP.

**Comment by dneto0** [comment]
Now also has support for SPIR-V assembly modules. 

But dependencies are still probably messed up.  So still WIP.

**Comment by AWoloszyn** [comment]
Closing, as this is slightly out of date!

**Pull request closed without merging**
